version: '3'
services:
 app:
   image: luna:latest
   command: "/usr/sbin/sshd -D"
   ports:
     - "2222:22"
     - "8000:8000"
   volumes:
     - ./app:/app
     - ./media:/media
     - ./static:/static
     - ./scripts:/scripts
   depends_on:
     - luna_db

 luna_db:
   image: postgres:latest
   env_file: env_files/postgres.env
   ports:
     - "5432:5432"
   volumes:
     - luna_db:/var/lib/postgresql/data

volumes:
 luna_db: